omod DRONE-INSTANCE is
  protecting GENERAL-FRAMEWORK .
  protecting GEOMETRY . 
  protecting DRONE-BRAIN .

  subsort loc < Position .
  subsort Dir8 < Dir .

  op wind : loc -> Disturbance [ctor] .
  op d : Nat -> Oid [ctor] .

  vars P P1 P2 EP : loc .
  vars S B : Rat .
  vars H : Dir8 .
  vars W : loc .
  var  DT : Rat .

  eq hasReliablePerception(P) = distSq(P, v(15, 15)) <= 64 .

  eq inCommunicationRange(P1, P2) = distSq(P1, P2) <= 25 .

  eq updatePhysicalState(P, S, H, wind(W), DT) = P + ((dirToVec(H) * (S * DT)) + (W * DT)) .

  eq estimateNextPosition(EP, S, H, DT) = EP + (dirToVec(H) * (S * DT)) .
  eq isCollision(P1, P2) = distSq(P1, P2) < 1/10 .

  eq possibleDisturbances = wind(v(0, 1/10)) ; wind(v(1/10, 0)) ; wind(v(-1/10, 0)) .

endom