omod DRONE is
  protecting GEOMETRY .

  sorts DroneMsg DroneMsgSet .
  subsort DroneMsg < DroneMsgSet .
  op emptyMsg : -> DroneMsgSet [ctor] .
  op _;_ : DroneMsgSet DroneMsgSet -> DroneMsgSet [assoc comm id: emptyMsg] .
  
  op dMsg : Oid Vector Rat -> DroneMsg [ctor] . 

  class Drone | pos : Vector, estPos : Vector,
                goalPos : Vector, belief : Rat,
		speed : Rat, heading : Dir8, inbox : DroneMsgSet .

  op d : Nat -> Oid [ctor] .

  var O : Oid . 
  var V : Vector . 
  var B : Rat .

  op getPos : Object -> Vector .
  eq getPos(< O : Drone | pos : V >) = V .

  op genMessage : Object -> DroneMsg .
  eq genMessage(< O : Drone | estPos : V, belief : B >) = dMsg(O, V, B) .
  
endom