mod DRONE-BRAIN is
  protecting BROADCAST .
  protecting GENERAL-FRAMEWORK .

  vars P P2 G EP NEW-EP LEADER-P : Position .
  vars O O2 : Oid .
  vars B B2 S currDist nextDist NEW-B LEADER-B : Rat .
  vars H H1 H2 NEW-H : Dir .
  var AS : AttributeSet .
  var MS : AgentMsgSet .
  var M BEST-MSG : AgentMsg .
  var D : Object .

  op think : Object -> Object .
  ceq think(D) =
      < O : Agent | pos : P,
                    estPos : NEW-EP,
                    goalPos : G,
                    belief : NEW-B,
                    speed : calcSpeed(NEW-EP, NEW-H, NEW-B, MS), 
                    heading : NEW-H,
                    inbox : emptyMsg >
      if < O : Agent | pos : P, estPos : EP, goalPos : G, belief : B, speed : S, heading : H, inbox : MS > := D
      /\ NEW-EP := calcEstPos(EP, MS)
      /\ NEW-B  := calcBelief(B, MS)
      /\ NEW-H  := bestDir(NEW-EP, G) .
      
  op calcBelief : Rat AgentMsgSet -> Rat .
  op calcEstPos : Position AgentMsgSet -> Position .
  op calcSpeed : Position Dir Rat AgentMsgSet -> Rat .
  op bestDir : Position Position -> Dir .
  
endm