mod DRONE-SYSTEM is
  protecting DRONE-BRAIN .
  protecting NAT .

  sort System .
  op { _ , _ } : Configuration Nat -> System [ctor] .

  vars C C' : Configuration . 
  var O : Object .
  vars P P' EP G W BASE-P : Vector .
  vars B S R : Rat .
  vars H NEW-H : Dir8 .
  var AS AS' : AttributeSet .
  var ID ID1 : Oid .
  var T : Nat .
  var MS : DroneMsgSet .

  op radioRange : -> Rat .
  eq radioRange = 5 .

  op signalRecovery : Configuration Vector Rat -> Configuration .
  eq signalRecovery(none, BASE-P, R) = none .
  eq signalRecovery(< ID : Drone | pos : P, estPos : EP, belief : B, AS > C, BASE-P, R) = 
     (if distSq(P, BASE-P) <= (R * R) then < ID : Drone | pos : P, estPos : P, belief : 1/1, AS >
      else < ID : Drone | pos : P, estPos : EP, belief : B, AS >
      fi) signalRecovery(C, BASE-P, R) .

  op doStep : Configuration Vector -> Configuration .
  eq doStep(C, W) = moveAll(thinkAll(broadcastAll(signalRecovery(C, v(5, 5), 5), radioRange)), W) .

  op thinkAll : Configuration -> Configuration .
  eq thinkAll(none) = none .
  eq thinkAll(O C) = think(O) thinkAll(C) . 

  op moveAll : Configuration Vector -> Configuration .
  eq moveAll(none, W) = none .
  eq moveAll((< ID : Drone | pos : P, estPos : EP, belief : B, speed : S, heading : H, AS > C), W) =
     (< ID : Drone | 
         pos : ((P + (dirToVec(H) * S)) + W), 
         estPos : (EP + (dirToVec(H) * S)), 
         belief : (if B > 1/10 then B - 1/10 else 0 fi), 
         speed : S, heading : H, AS >) 
     moveAll(C, W) .


  rl [tick-calm] : { C , T } => { doStep(C, v(0, 1/10)) , T + 1 } .
  rl [tick-east] : { C , T } => { doStep(C, v(1/10, 0)) , T + 1 } .
  rl [tick-west] : { C , T } => { doStep(C, v(-1/10, 0)) , T + 1 } .


  ceq { < ID : Drone | pos : P, AS > < ID1 : Drone | pos : P', AS' > C , T } = { C , T } 
    if distSq(P, P') < 1/4 .

endm