mod DRONE-BRAIN is
  protecting BROADCAST .

  vars P P2 G EP NEW-EP LEADER-P : Vector .
  vars O O2 : Oid .
  vars B B2 S currDist nextDist NEW-B LEADER-B : Rat .
  vars H H1 H2 NEW-H : Dir8 .
  var AS : AttributeSet .
  var MS : DroneMsgSet .
  var M BEST-MSG : DroneMsg .

  op muLost : Rat -> Rat .
  eq muLost(B) = if B <= 1/4 then 1 else (if B >= 1/2 then 0 else (1/2 - B) * 4 fi) fi .

  op muWary : Rat -> Rat .
  eq muWary(B) = if B <= 1/4 or B >= 3/4 then 0 else (if B <= 1/2 then (B - 1/4) * 4 else (3/4 - B) * 4 fi) fi .

  op muConfident : Rat -> Rat .
  eq muConfident(B) = if B <= 1/2 then 0 else (if B >= 3/4 then 1 else (B - 1/2) * 4 fi) fi .

  op fuzzyScale : Rat -> Rat .
  eq fuzzyScale(B) = (muConfident(B) * 1) + (muWary(B) * 1/2) + (muLost(B) * 1/10) .

  op dirToVec : Dir8 -> Vector .
  eq dirToVec(N)    = v(0, 1) .
  eq dirToVec(E)    = v(1, 0) .
  eq dirToVec(S)    = v(0, -1) .
  eq dirToVec(W)    = v(-1, 0) .
  eq dirToVec(NE)   = v(7/10, 7/10) .
  eq dirToVec(SE)   = v(7/10, -7/10) .
  eq dirToVec(SW)   = v(-7/10, -7/10) .
  eq dirToVec(NW)   = v(-7/10, 7/10) .
  eq dirToVec(stop) = v(0, 0) .

  op getBelief : DroneMsg -> Rat .
  eq getBelief(dMsg(O, P, B)) = B .

  op getPos : DroneMsg -> Vector .
  eq getPos(dMsg(O, P, B)) = P .

  op findBestMsg : DroneMsgSet -> DroneMsg .
  eq findBestMsg(emptyMsg) = dMsg(d(999), v(0,0), 0) .
  ceq findBestMsg(dMsg(O2, P2, B2) ; MS) =
     if B2 > getBelief(M) then dMsg(O2, P2, B2) else M fi 
     if M := findBestMsg(MS) .

  op findDanger : Vector Dir8 DroneMsgSet -> DroneMsg .
  eq findDanger(P, H, emptyMsg) = dMsg(d(999), v(1000, 1000), 0) .
  ceq findDanger(P, H, dMsg(O2, P2, B2) ; MS) =
     if distSq(P + dirToVec(H), P2) < distSq(P + dirToVec(H), getPos(M))
     then dMsg(O2, P2, B2) else M fi 
     if M := findDanger(P, H, MS) .

  op calcSpeed : Rat Rat Rat -> Rat .
  eq calcSpeed(currDist, nextDist, B) = 
    if currDist < 1 then 0
    else (if nextDist < currDist then 1/4 else 1/2 fi) * fuzzyScale(B) fi .

  op think : Object -> Object .
  ceq think(< O : Drone | pos : P, estPos : EP, goalPos : G, belief : B, speed : S, heading : H, inbox : MS, AS >) =
            < O : Drone | pos : P, 
                          estPos : NEW-EP, 
                          goalPos : G, 
                          belief : NEW-B, 
                          speed : calcSpeed(distSq(NEW-EP, getPos(M)), distSq(NEW-EP + dirToVec(NEW-H), getPos(M)), NEW-B), 
                          heading : NEW-H, 
                          inbox : emptyMsg, AS >
    if BEST-MSG := findBestMsg(MS)
    /\ LEADER-B := getBelief(BEST-MSG)
    /\ LEADER-P := getPos(BEST-MSG)
    
    /\ NEW-EP := (if (B < 1/20) and (LEADER-B > 9 / 10) then LEADER-P else EP fi)
    /\ NEW-B  := (if (B < 1/20) and (LEADER-B > 9 / 10) then (LEADER-B * 9/10) else B fi)
    
    /\ NEW-H := bestDir(NEW-EP, G) 
    /\ M := findDanger(NEW-EP, NEW-H, MS) .    
    
  op betterDir : Vector Vector Dir8 Dir8 -> Dir8 .
  eq betterDir(P, G, H1, H2) = 
    if distSq(P + dirToVec(H1), G) < distSq(P + dirToVec(H2), G) 
    then H1 else H2 fi .

  op bestDir : Vector Vector -> Dir8 .
  eq bestDir(P, G) = 
    betterDir(P, G, 
      betterDir(P, G, 
        betterDir(P, G, N, NE), 
        betterDir(P, G, E, SE)
      ), 
      betterDir(P, G, 
        betterDir(P, G, S, SW), 
        betterDir(P, G, W, NW)
      )
    ) .
endm