mod DRONE-SYSTEM is
  protecting DRONE-BRAIN .
  protecting NAT .

  sort System .
  op { _ , _ } : Configuration Nat -> System [ctor] .

  vars C C' : Configuration . 
  var O : Object .
  vars P P' EP G W BASE-P : Vector .
  vars B S R : Rat .
  vars H NEW-H : Dir8 .
  var AS AS' : AttributeSet .
  var ID ID1 : Oid .
  var T : Nat .
  var MS : DroneMsgSet .

  op radioRange : -> Rat .
  eq radioRange = 5 .

  ---add area where there is perfect signal. if drone goes in to that area then belife is set to 1 and estpost to actualpos
  op signalRecovery : Configuration Vector Rat -> Configuration .
  eq signalRecovery(none, BASE-P, R) = none .
  eq signalRecovery(< ID : Drone | pos : P, estPos : EP, belief : B, AS > C, BASE-P, R) = 
     (if distSq(P, BASE-P) <= (R * R) then < ID : Drone | pos : P, estPos : P, belief : 1/1, AS >
      else < ID : Drone | pos : P, estPos : EP, belief : B, AS >
      fi) signalRecovery(C, BASE-P, R) .

  ---first check if you recovered signal. then broadcast information. make desition and apply that desition
  op doStep : Configuration Vector -> Configuration .
  eq doStep(C, W) = moveAll(thinkAll(broadcastAll(signalRecovery(C, v(15, 15), 8), radioRange)), W) .

  ---iterate on drones for each to think
  op thinkAll : Configuration -> Configuration .
  eq thinkAll(none) = none .
  eq thinkAll(O C) = think(O) thinkAll(C) . 

  op moveAll : Configuration Vector -> Configuration .
  eq moveAll(none, W) = none .
  eq moveAll((< ID : Drone | pos : P, estPos : EP, belief : B, speed : S, heading : H, AS > C), W) =
     (< ID : Drone | 
         pos : ((P + (dirToVec(H) * S)) + W), ---new position is calculated using actual position directoin speed and wind
         estPos : (EP + (dirToVec(H) * S)),   ---estPost can not mesure wind or know actual position. so it uses estpos dir and speed
         belief : (if B > 1/50 then B - 1/50 else 0 fi),  ---belife degrades
         speed : S, heading : H, AS >) ---speed was set in brain so no change 
     moveAll(C, W) .

  ---there can be many types of wind. which creates nondeterminism.
  rl [tick-calm] : { C , T } => { doStep(C, v(0, 1/10)) , T + 1 } .
  rl [tick-east] : { C , T } => { doStep(C, v(1/10, 0)) , T + 1 } .
  rl [tick-west] : { C , T } => { doStep(C, v(-1/10, 0)) , T + 1 } .

  --- 1. Helper: Does this drone hit ANYONE in the provided configuration?
  op isHit : Object Configuration -> Bool .
  ceq isHit(< ID : Drone | pos : P, AS >, < ID1 : Drone | pos : P', AS' > C) = true 
    if ID =/= ID1 /\ distSq(P, P') < 1/10 .
  eq isHit(O, C) = false [owise] .

  --- 2. Helper: Rebuild the configuration, dropping crashed drones
  op solve : Configuration Configuration -> Configuration .
  eq solve(none, C') = none .
  eq solve(O C, C') = 
     (if isHit(O, C') then none else O fi) solve(C, C') .

  --- 3. THE REPLACEMENT: Automatic global cleanup
  ceq { O C , T } = { solve(O C, O C) , T } 
    if isHit(O, C) .
    

endm