search [1] in SWARM-ANALYSIS : {
  < d(1) : Agent | pos : v(0, 0), estPos : v(0, 0), goalPos : v(20, 20), 
                   belief : 1/1, speed : 1/1, heading : NE, inbox : emptyMsg >
  < d(2) : Agent | pos : v(1, 0), estPos : v(1, 0), goalPos : v(20, 20), 
                   belief : 9/10, speed : 1/1, heading : NE, inbox : emptyMsg >
  < d(3) : Agent | pos : v(0, 1), estPos : v(0, 1), goalPos : v(20, 20), 
                   belief : 9/10, speed : 1/1, heading : NE, inbox : emptyMsg >
  < d(4) : Agent | pos : v(2, 2), estPos : v(8, 8), goalPos : v(20, 20), 
                   belief : 1/10, speed : 1/1, heading : NE, inbox : emptyMsg >
  < d(5) : Agent | pos : v(1, 1), estPos : v(1, 1), goalPos : v(20, 20), 
                   belief : 1/1, speed : 1/1, heading : NE, inbox : emptyMsg >
} =>* { C } 
such that objectiveAccomplished({ C }, 5) >= 2/5 .