omod FUSION-LOGIC is
  protecting GEOMETRY .
  protecting DRONE-BRAIN .

  subsort loc < Position .
  subsort Dir3D < Dir .

  vars O : Oid .
  vars V : loc .
  vars B W : Rat .
  var MS : Configuration .

  op trustThreshold : -> Rat .
  eq trustThreshold = 1/1 . 

  op consensusBonus : -> Rat .
  eq consensusBonus = 1/50 .

  op sumWeights : Configuration -> Rat .
  eq sumWeights(none) = 0/1 .
  eq sumWeights(msg(O, V, B) MS) = B + sumWeights(MS) .

  op sumWPos : Configuration -> Position .
  eq sumWPos(none) = v(0, 0, 0) .
  eq sumWPos(msg(O, V, B) MS) = (V * B) + sumWPos(MS) .

  ceq calcEstPos(V, MS) = 
    (if (W >= trustThreshold) then (sumWPos(MS) / W) else V fi)
    if W := sumWeights(MS) .

  ceq calcBelief(B, MS) = 
    (if (W >= trustThreshold) 
     then (if (B + (consensusBonus * W) > 1/1) then 1/1 else (B + (consensusBonus * W)) fi) 
     else (if B > 1/50 then B - 1/50 else 0 fi) fi)
    if W := sumWeights(MS) .
    
endom