omod GENERAL-FRAMEWORK is
  protecting NAT .
  protecting RAT .

  sorts Position Dir Disturbance DisturbanceSet .
  subsort Disturbance < DisturbanceSet .
  
  op noneDist : -> DisturbanceSet [ctor] .
  op _;_ : DisturbanceSet DisturbanceSet -> DisturbanceSet [assoc comm id: noneDist] .

  sorts AgentMsg AgentMsgSet .
  subsort AgentMsg < AgentMsgSet .
  op emptyMsg : -> AgentMsgSet [ctor] .
  op _;_ : AgentMsgSet AgentMsgSet -> AgentMsgSet [assoc comm id: emptyMsg] .
  op msg : Oid Position Rat -> AgentMsg [ctor] . 

  class Agent | pos : Position, estPos : Position, goalPos : Position, 
                belief : Rat, speed : Rat, heading : Dir, inbox : AgentMsgSet .

  sort System .
  op { _|_ } : Configuration Nat -> System [ctor] .

  vars C C' Acc : Configuration . 
  var O : Object .
  vars P EP P' : Position .
  vars B S : Rat .
  var H : Dir .
  var AS AS' : AttributeSet .
  vars ID ID1 : Oid .
  var T N : Nat .
  var D : Disturbance .
  var DS : DisturbanceSet .

  op hasReliablePerception : Position -> Bool .
  op inCommunicationRange : Position Position -> Bool .
  op updatePhysicalState : Position Rat Dir Disturbance -> Position .
  op estimateNextPosition : Position Rat Dir -> Position .
  op isCollision : Position Position -> Bool .
  op possibleDisturbances : -> DisturbanceSet .

  op perceiveEnvironment : Configuration -> Configuration .
  eq perceiveEnvironment(none) = none .
  eq perceiveEnvironment(< ID : Agent | pos : P, estPos : EP, belief : B > C) = 
     (if hasReliablePerception(P) 
      then < ID : Agent | pos : P, estPos : P, belief : 1/1 >
      else < ID : Agent | pos : P, estPos : EP, belief : B > fi) 
     perceiveEnvironment(C) .

  op broadcastAll : Configuration -> Configuration .

  op thinkAll : Configuration -> Configuration .
  op think : Object -> Object . 
  eq thinkAll(none) = none .
  eq thinkAll(O C) = think(O) thinkAll(C) .

  op applyPhysics : Configuration Disturbance -> Configuration .
  eq applyPhysics(none, D) = none .
  eq applyPhysics((< ID : Agent | pos : P, estPos : EP, speed : S, heading : H > C), D) =
     (< ID : Agent | 
         pos : updatePhysicalState(P, S, H, D),
         estPos : estimateNextPosition(EP, S, H) >) 
     applyPhysics(C, D) .

  op applyPhysicsAcc : Configuration Configuration Disturbance -> Configuration .
  eq applyPhysicsAcc(none, Acc, D) = Acc .
  eq applyPhysicsAcc((< ID : Agent | pos : P, estPos : EP, speed : S, heading : H > C), Acc, D) =
     applyPhysicsAcc(
        C, 
        Acc (< ID : Agent | 
         pos : updatePhysicalState(P, S, H, D),
         estPos : estimateNextPosition(EP, S, H) >),
        D
      ) .

  op applyPhysics : Configuration Disturbance -> Configuration .
  eq applyPhysics(C, D) = applyPhysicsAcc(C, none, D) .

  op performStep : Configuration Disturbance -> Configuration .
  eq performStep(C, D) = broadcastAll(applyPhysics(thinkAll(perceiveEnvironment(C)), D)) .

  op objectiveAccomplished : System -> Bool .

  crl [performBigStep] : { C | N } => { performStep(C, D) | N + 1 } 
      if objectiveAccomplished({ C | N }) /\ D ; DS := possibleDisturbances .

  op isHit : Object Configuration -> Bool .
  ceq isHit(< ID : Agent | pos : P, AS > , < ID1 : Agent | pos : P' , AS' > C) = true 
    if ID =/= ID1 /\ isCollision(P , P') .
  eq isHit(O, C) = false [owise] .

  op solve : Configuration Configuration -> Configuration .
  eq solve(none, C') = none .
  eq solve(O C, C') = (if isHit(O, C') then none else O fi) solve(C, C') .

  ceq { O C | N } = { solve(O C, O C) | N } if isHit(O, C) .

endom