omod GENERAL-FRAMEWORK is
  protecting NAT .
  protecting RAT .

  sorts Dir .

  sorts Position Disturbance DisturbanceSet .
  subsort Disturbance < DisturbanceSet .
  
  op noneDist : -> DisturbanceSet [ctor] .
  op _;_ : DisturbanceSet DisturbanceSet -> DisturbanceSet [assoc comm id: noneDist] .

  msg msg : Oid Position Rat -> Msg .

  class Drone | pos : Position, estPos : Position, goalPos : Position, 
                belief : Rat, speed : Rat, heading : Dir, inbox : Configuration .

  sort System .
  op { _ } : Configuration -> System [ctor] .

  vars C C' Acc : Configuration . 
  var O : Object .
  vars P EP P' : Position .
  vars B S : Rat .
  var H : Dir .
  var AS AS' : AttributeSet .
  vars ID ID1 : Oid .
  var T N : Nat .
  var D : Disturbance .
  var DS : DisturbanceSet .

  op period : -> Rat .

  op hasReliablePerception : Position -> Bool .
  op inCommunicationRange : Position Position -> Bool .
  op updatePhysicalState : Position Rat Dir Disturbance Rat  -> Position .
  op estimateNextPosition : Position Rat Dir Rat -> Position .
  op crashThresholdSq : -> Rat .
  op possibleDisturbances : -> DisturbanceSet .

  op broadcastAll : Configuration -> Configuration .

  op thinkAll : Configuration -> Configuration .
  op think : Object -> Object . 
  eq thinkAll(none) = none .
  eq thinkAll(O C) = think(O) thinkAll(C) .

  op applyPhysicsAcc : Configuration Configuration Disturbance -> Configuration .
  
  eq applyPhysicsAcc(none, Acc, D) = Acc .
  
  eq applyPhysicsAcc((< ID : Drone | pos : P, speed : S, heading : H > C), Acc, D) =
     applyPhysicsAcc(
        C, 
        Acc (< ID : Drone | 
                pos : updatePhysicalState(P, S, H, D, period) >),
        D
      ) .

  op applyPhysics : Configuration Disturbance -> Configuration .
  eq applyPhysics(C, D) = applyPhysicsAcc(C, none, D) .

  op resolveCollisions : Configuration -> Configuration .

  crl [performSyncStep] : 
      { C } => { broadcastAll(applyPhysics(resolveCollisions(thinkAll(C)), D)) } 
      if D ; DS := possibleDisturbances .

endom