fmod GEOMETRY is
  protecting RAT .
  
  sorts loc .
  op v : Rat Rat -> loc [ctor] .

  sort Dir8 .
  ops N NE E SE S SW W NW stop : -> Dir8 [ctor] .

  op dirToVec : Dir8 -> loc .
  eq dirToVec(N)    = v(0, 1) .
  eq dirToVec(E)    = v(1, 0) .
  eq dirToVec(S)    = v(0, -1) .
  eq dirToVec(W)    = v(-1, 0) .
  eq dirToVec(NE)   = v(7/10, 7/10) .
  eq dirToVec(SE)   = v(7/10, -7/10) .
  eq dirToVec(SW)   = v(-7/10, -7/10) .
  eq dirToVec(NW)   = v(-7/10, 7/10) .
  eq dirToVec(stop) = v(0, 0) .

  vars X Y X1 Y1 X2 Y2 R  : Rat .

  op _+_ : loc loc -> loc .
  eq v(X1, Y1) + v(X2, Y2) = v(X1 + X2, Y1 + Y2) .

  op _-_ : loc loc -> loc .
  eq v(X1, Y1) - v(X2, Y2) = v(X1 - X2, Y1 - Y2) .

  op _*_ : loc Rat -> loc .
  eq v(X, Y) * R = v(X * R, Y * R) .

  op _/_ : loc Rat -> loc .
  eq v(X, Y) / R = v(X / R, Y / R) .

  op distSq : loc loc -> Rat .
  eq distSq(v(X1, Y1), v(X2, Y2)) = ((X1 - X2) * (X1 - X2)) + ((Y1 - Y2) * (Y1 - Y2)) .

endfm