omod SWARM-META-ANALYSIS is
  protecting META-LEVEL .
  protecting SWARM-ANALYSIS .

  sort MetaState .

  op [ _ | _ , _ ] : System Nat Nat -> MetaState [ctor] . 

  vars S S' : System .
  var C : Configuration .
  vars N IC : Nat .
  var T' : Term .   
  var TY : Type .   
  var SUB : Substitution .   

  op initAnalysis : Configuration -> MetaState .
  eq initAnalysis(C) = [ { C } | 0 , countAgents(C) ] .

  op metaObjectiveAccomplished : Configuration Nat -> Bool .
  eq metaObjectiveAccomplished(C, IC) = swarmSuccess(C, IC) >= 9/10 .

  crl [trackedStep] : 
    [ { C } | N , IC ] => [ S' | N + 1 , IC ] 
    if not metaObjectiveAccomplished(C, IC)
                /\ { T' , TY , SUB } := metaApply(
                             upModule('SWARM-ANALYSIS, false), 
                             upTerm({ C }), 
                             'performBigStep, 
                             none, 0
                    )
                /\ S' := downTerm(T', { none }) .
endom