mod PROPAGATION is
  protecting QUADTREE .

  vars NW NE SW SE : Tree .
  vars B : Box .
  vars SenderPos P EP : Vector .
  vars R : Rat .
  var Src : Oid .
  var AS : AttributeSet .
  var I : DroneMsgSet .
  var Data : Rat .
  var O : Oid .
  var M : DroneMsg .

  op deliver : DroneMsg Vector Rat Tree -> Tree .

  eq deliver(M, SenderPos, R, empty) = empty .

  ceq deliver(M, SenderPos, R, node(B, NW, NE, SW, SE)) =
      node(B, deliver(M, SenderPos, R, NW),
              deliver(M, SenderPos, R, NE),
              deliver(M, SenderPos, R, SW),
              deliver(M, SenderPos, R, SE))
    if intersects(SenderPos, R, B) .

  ceq deliver(dMsg(Src, EP, Data), SenderPos, R, leaf(< O : Drone | pos: P, inbox: I, AS >)) =
      leaf(< O : Drone | pos: P, inbox: (I ; dMsg(Src, EP, Data)), AS >)
    if distSq(SenderPos, P) <= (R * R) /\ O =/= Src .

  eq deliver(M, SenderPos, R, T:Tree) = T:Tree [owise] .
endm