mod SWARM-ANALYSIS is
  protecting DRONE-SYSTEM .

  vars C : Configuration .
  vars P G : Vector .
  vars N T : Nat .
  var OID : Oid .
  var AS : AttributeSet .
  var OBJ : Object .
  vars X1 Y1 X2 Y2 : Rat .

  --- Manhattan Distance: |X1 - X2| + |Y1 - Y2|
  op manhattanDist : Vector Vector -> Rat .
  eq manhattanDist(v(X1, Y1), v(X2, Y2)) = abs(X1 - X2) + abs(Y1 - Y2) .

  --- Linear success: 1 - (Current Distance / Max Distance)
  --- Assumes max Manhattan distance of 40 (from 0,0 to 20,20)
  op droneSuccess : Object -> Rat .
  eq droneSuccess(< OID : Drone | pos : P, goalPos : G, AS >) = 
     1 - (manhattanDist(P, G) / 40) .
     
  op sumSwarm : Configuration -> Rat .
  eq sumSwarm(none) = 0 .
  eq sumSwarm(OBJ C) = droneSuccess(OBJ) + sumSwarm(C) .

  op objectiveAccomplished : System Nat -> Rat .
  eq objectiveAccomplished({ C , T }, N) = sumSwarm(C) / N .
  
endm