mod SWARM-ANALYSIS is
  protecting DRONE-INSTANCE .

  vars C : Configuration .
  vars P G : Vector .
  vars N T : Nat .
  var OID : Oid .
  var AS : AttributeSet .
  var OBJ : Object .
  vars X1 Y1 X2 Y2 : Rat .

  op manhattanDist : Vector Vector -> Rat .
  eq manhattanDist(v(X1, Y1), v(X2, Y2)) = abs(X1 - X2) + abs(Y1 - Y2) .

  op droneSuccess : Object -> Rat .
  --- Notice the class is now Agent
  eq droneSuccess(< OID : Agent | pos : P, goalPos : G, AS >) = 
     1 - (manhattanDist(P, G) / 40) .
     
  op sumSwarm : Configuration -> Rat .
  eq sumSwarm(none) = 0 .
  eq sumSwarm(OBJ C) = droneSuccess(OBJ) + sumSwarm(C) .

  op objectiveAccomplished : System Nat -> Rat .
  eq objectiveAccomplished({ C }, N) = sumSwarm(C) / N .
endm