omod BROADCAST is
  protecting GENERAL-FRAMEWORK .

  vars C-REM C-ALL : Configuration .
  vars ID S-ID : Oid .
  vars P S-P S-EP : Position .
  var S-B : Rat .

  op broadcastAll : Configuration -> Configuration .
  eq broadcastAll(C-ALL) = updateAll(C-ALL, C-ALL) .

  op updateAll : Configuration Configuration -> Configuration .
  eq updateAll(none, C-ALL) = none .
  eq updateAll((< ID : Drone | pos : P > C-REM), C-ALL) =
     < ID : Drone | inbox : collectMsgs(ID, P, C-ALL) > updateAll(C-REM, C-ALL) .

  op collectMsgs : Oid Position Configuration -> Configuration .
  eq collectMsgs(ID, P, none) = none .
  eq collectMsgs(ID, P, (< S-ID : Drone | pos : S-P, estPos : S-EP, belief : S-B > C-REM)) =
     (if (ID =/= S-ID) and inCommunicationRange(S-P, P) 
      then msg(S-ID, S-EP, S-B) 
      else none fi) collectMsgs(ID, P, C-REM) .

endom